services:
  database:
    image: mongo:latest
    container_name: workcodile-mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - workcodile-net

  backend:
    build:
      context: ./backend
      target: development
    container_name: workcodile-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app # Monta el código para desarrollo en tiempo real
      - /app/node_modules # No montar node_modules locales
    depends_on:
      - database
      - minio
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb://database:27017/workcodiledb}
      - PORT=${PORT:-3001}
      - JWT_SECRET=${JWT_SECRET:-WorkcoWord}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-workcodile-files}
      - MINIO_PUBLIC_ENDPOINT=localhost
      - GMAIL_USER=${GMAIL_USER} # Added for email functionality
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD} # Added for email functionality
    networks:
      - workcodile-net

  frontend:
    build:
      context: ./frontend
    container_name: workcodile-frontend
    ports:
      - "8080:80" # Expone el Nginx en el puerto 8080
    volumes:
      - ./frontend/src:/app/src # Monta el código para desarrollo en tiempo real
    depends_on:
      - backend
    networks:
      - workcodile-net

  minio:
    image: minio/minio:latest
    container_name: workcodile-minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Consola Web
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minioadmin123}
    command: server /data --console-address ":9001"
    networks:
      - workcodile-net

networks:
  workcodile-net:
    driver: bridge
