services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: workcodile-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app # Monta el código para desarrollo en tiempo real
      - /app/node_modules # No montar node_modules locales
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT:-3001}
      - JWT_SECRET=${JWT_SECRET:-WorkcoWord}
      - STORAGE_PROVIDER=${STORAGE_PROVIDER:-cpanel} # 'b2' or 'cpanel'
      # Backblaze B2 Credentials
      - B2_ENDPOINT_URL=${B2_ENDPOINT_URL}
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME:-WorkcodileBucket}
      - B2_NATIVE_PUBLIC_URL_PREFIX=${B2_NATIVE_PUBLIC_URL_PREFIX}
      # cPanel Credentials
      - CPANEL_SERVER=${CPANEL_SERVER:-https://codetechilo.com:2083}
      - CPANEL_USER=${CPANEL_USER:-codetech}
      - CPANEL_API_TOKEN=${CPANEL_API_TOKEN:-your_cpanel_api_token}
      - CPANEL_PUBLIC_URL=${CPANEL_PUBLIC_URL:-https://codetechilo.com/workcodile/files}
      - CPANEL_UPLOAD_DIR=${CPANEL_UPLOAD_DIR:-/public_html/storage}
      # Email Credentials
      - GMAIL_USER=${GMAIL_USER} # Added for email functionality
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD} # Added for email functionality
    networks:
      - workcodile-net

  frontend:
    build:
      context: ./frontend
    container_name: workcodile-frontend
    ports:
      - "8080:80" # Expone el Nginx en el puerto 8080
    volumes:
      - ./frontend/src:/app/src # Monta el código para desarrollo en tiempo real
    depends_on:
      - backend
    networks:
      - workcodile-net



networks:
  workcodile-net:
    driver: bridge
