import { Course } from './curriculum-colors'

// TODO BACKEND: El endpoint GET /api/courses debe devolver esta estructura
export const MOCK_CURRICULUM: Course[] = [
  { _id: 'IS-124', code: 'IS-124', name: 'REDACCION Y COMUNICACION', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-127', code: 'IS-127', name: 'BIOLOGIA Y MEDIO AMBIENTE', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-122', code: 'IS-122', name: 'MATEMATICA I', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-123', code: 'IS-123', name: 'METODOLOGIA Y TECNICAS DE ESTUDIO UNIVERSITARIO', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-121', code: 'IS-121', name: 'FUNDAMENTOS DE PROGRAMACION', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-125', code: 'IS-125', name: 'FILOSOFIA', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-126', code: 'IS-126', name: 'SOCIOLOGIA Y REALIDAD NACIONAL', cycle: 1, prerequisites: [], type: 'basic' },
  { _id: 'IS-225', code: 'IS-225', name: 'MATEMATICAS DISCRETAS I', cycle: 2, prerequisites: [], type: 'basic' },
  { _id: 'IS-226', code: 'IS-226', name: 'MATEMATICA II', cycle: 2, prerequisites: ['IS-122'], type: 'basic' },
  { _id: 'IS-224', code: 'IS-224', name: 'ALGEBRA LINEAL', cycle: 2, prerequisites: ['IS-122'], type: 'basic' },
  { _id: 'IS-223', code: 'IS-223', name: 'PROGRAMACION ORIENTADA A OBJETOS I', cycle: 2, prerequisites: ['IS-121'], type: 'basic' },
  { _id: 'IS-221', code: 'IS-221', name: 'ESTRUCTURA DE DATOS', cycle: 2, prerequisites: ['IS-121'], type: 'basic' },
  { _id: 'IS-227', code: 'IS-227', name: 'ESTADISTICA BASICA', cycle: 2, prerequisites: [], type: 'basic' },
  { _id: 'IS-228', code: 'IS-228', name: 'ETICA', cycle: 2, prerequisites: [], type: 'basic' },
  { _id: 'IS-325', code: 'IS-325', name: 'MATEMATICAS DISCRETAS II', cycle: 3, prerequisites: ['IS-225'], type: 'basic' },
  { _id: 'IS-324', code: 'IS-324', name: 'MATEMATICA III', cycle: 3, prerequisites: ['IS-226'], type: 'basic' },
  { _id: 'IS-327', code: 'IS-327', name: 'FISICA ELECTRICA', cycle: 3, prerequisites: [], type: 'basic' },
  { _id: 'IS-322', code: 'IS-322', name: 'PROGRAMACION ORIENTADA A OBJETOS II', cycle: 3, prerequisites: ['IS-223'], type: 'basic' },
  { _id: 'IS-323', code: 'IS-323', name: 'FUNDAMENTOS DE SISTEMAS DE INFORMACION', cycle: 3, prerequisites: ['IS-223'], type: 'basic' },
  { _id: 'IS-321', code: 'IS-321', name: 'ANALISIS Y DISENO DE ALGORITMOS', cycle: 3, prerequisites: ['IS-221'], type: 'basic' },
  { _id: 'IS-326', code: 'IS-326', name: 'PROBABILIDADES', cycle: 3, prerequisites: ['IS-227'], type: 'basic' },
  { _id: 'IS-424', code: 'IS-424', name: 'SISTEMAS OPERATIVOS', cycle: 4, prerequisites: [], type: 'basic' },
  { _id: 'IS-425', code: 'IS-425', name: 'MATEMATICA IV', cycle: 4, prerequisites: ['IS-324'], type: 'basic' },
  { _id: 'IS-426', code: 'IS-426', name: 'CIRCUITOS ELECTRICOS Y ELECTRONICOS', cycle: 4, prerequisites: [], type: 'basic' },
  { _id: 'IS-427', code: 'IS-427', name: 'INVESTIGACION OPERATIVA I', cycle: 4, prerequisites: [], type: 'basic' },
  { _id: 'IS-422', code: 'IS-422', name: 'ANALISIS Y DISENO DE SISTEMAS I', cycle: 4, prerequisites: [], type: 'basic' },
  { _id: 'IS-421', code: 'IS-421', name: 'ALGORITMOS PARALELOS', cycle: 4, prerequisites: ['IS-321'], type: 'basic' },
  { _id: 'IS-423', code: 'IS-423', name: 'BASE DE DATOS I', cycle: 4, prerequisites: [], type: 'basic' },
  { _id: 'IS-524', code: 'IS-524', name: 'APLICACIONES WEB I', cycle: 5, prerequisites: [], type: 'basic' },
  { _id: 'IS-525', code: 'IS-525', name: 'METODOS NUMERICOS', cycle: 5, prerequisites: ['IS-425'], type: 'basic' },
  { _id: 'IS-526', code: 'IS-526', name: 'SISTEMAS DIGITALES', cycle: 5, prerequisites: ['IS-426'], type: 'basic' },
  { _id: 'IS-527', code: 'IS-527', name: 'INVESTIGACION OPERATIVA II', cycle: 5, prerequisites: ['IS-427'], type: 'basic' },
  { _id: 'IS-522', code: 'IS-522', name: 'ANALISIS Y DISENO DE SISTEMAS II', cycle: 5, prerequisites: ['IS-422'], type: 'basic' },
  { _id: 'IS-521', code: 'IS-521', name: 'SISTEMAS DISTRIBUIDOS', cycle: 5, prerequisites: ['IS-421'], type: 'basic' },
  { _id: 'IS-523', code: 'IS-523', name: 'BASE DE DATOS II', cycle: 5, prerequisites: ['IS-423'], type: 'basic' },
  { _id: 'IS-624', code: 'IS-624', name: 'APLICACIONES WEB II', cycle: 6, prerequisites: ['IS-524'], type: 'basic' },
  { _id: 'IS-625', code: 'IS-625', name: 'REALIDAD AUMENTADA', cycle: 6, prerequisites: [], type: 'basic' },
  { _id: 'IS-626', code: 'IS-626', name: 'ARQUITECTURA DE COMPUTADORAS', cycle: 6, prerequisites: ['IS-526'], type: 'basic' },
  { _id: 'IS-623', code: 'IS-623', name: 'PROGRAMACION DE DISPOSITIVOS MOVILES I', cycle: 6, prerequisites: [], type: 'basic' },
  { _id: 'IS-621', code: 'IS-621', name: 'INGENIERIA DE SOFTWARE', cycle: 6, prerequisites: ['IS-522', 'IS-523'], type: 'basic' },
  { _id: 'IS-622', code: 'IS-622', name: 'BUSINESS INTELLIGENCE', cycle: 6, prerequisites: ['IS-523'], type: 'basic' },
  { _id: 'IS-721', code: 'IS-721', name: 'DATA MINING', cycle: 7, prerequisites: [], type: 'basic' },
  { _id: 'IS-724', code: 'IS-724', name: 'PROGRAMACION DE VIDEO JUEGOS I', cycle: 7, prerequisites: [], type: 'basic' },
  { _id: 'IS-726', code: 'IS-726', name: 'LENGUAJE DE BAJO NIVEL', cycle: 7, prerequisites: ['IS-626'], type: 'basic' },
  { _id: 'IS-723', code: 'IS-723', name: 'PROGRAMACION DE DISPOSITIVOS MOVILES II', cycle: 7, prerequisites: ['IS-623'], type: 'basic' },
  { _id: 'IS-722', code: 'IS-722', name: 'CALIDAD DE SOFTWARE', cycle: 7, prerequisites: ['IS-621'], type: 'basic' },
  { _id: 'IS-725', code: 'IS-725', name: 'REDES I', cycle: 7, prerequisites: [], type: 'basic' },
  { _id: 'IS-821', code: 'IS-821', name: 'CLOUD COMPUTING', cycle: 8, prerequisites: ['IS-721'], type: 'basic' },
  { _id: 'IS-824', code: 'IS-824', name: 'PROGRAMACION DE VIDEO JUEGOS II', cycle: 8, prerequisites: ['IS-724'], type: 'basic' },
  { _id: 'IS-823', code: 'IS-823', name: 'PROYECTO DE INVESTIGACION I', cycle: 8, prerequisites: [], type: 'basic' },
  { _id: 'IS-822', code: 'IS-822', name: 'PROCESAMIENTO DE IMAGENES Y VIDEOS', cycle: 8, prerequisites: [], type: 'basic' },
  { _id: 'IS-827', code: 'IS-827', name: 'ROBOTICA I', cycle: 8, prerequisites: [], type: 'basic' },
  { _id: 'IS-825', code: 'IS-825', name: 'INTERACCION HUMANO COMPUTADOR', cycle: 8, prerequisites: [], type: 'basic' },
  { _id: 'IS-826', code: 'IS-826', name: 'REDES II', cycle: 8, prerequisites: ['IS-725'], type: 'basic' },
  { _id: 'IS-924', code: 'IS-924', name: 'FORMACION DE EMPRESAS CON BASE TECNOLOGICA', cycle: 9, prerequisites: [], type: 'basic' },
  { _id: 'IS-922', code: 'IS-922', name: 'SEGURIDAD INFORMATICA', cycle: 9, prerequisites: [], type: 'basic' },
  { _id: 'IS-923', code: 'IS-923', name: 'PROYECTO DE INVESTIGACION II', cycle: 9, prerequisites: ['IS-823'], type: 'basic' },
  { _id: 'IS-921', code: 'IS-921', name: 'INTELIGENCIA ARTIFICIAL I', cycle: 9, prerequisites: ['IS-822'], type: 'basic' },
  { _id: 'IS-926', code: 'IS-926', name: 'ROBOTICA II', cycle: 9, prerequisites: ['IS-827'], type: 'basic' },
  { _id: 'IS-925', code: 'IS-925', name: 'PROYECTOS INFORMATICOS I', cycle: 9, prerequisites: [], type: 'basic' },
  { _id: 'IS-1022', code: 'IS-1022', name: 'AUDITORIA DE SISTEMAS DE INFORMACION', cycle: 10, prerequisites: ['IS-922'], type: 'basic' },
  { _id: 'IS-1023', code: 'IS-1023', name: 'SEGURIDAD DE LA INFORMACION', cycle: 10, prerequisites: ['IS-922'], type: 'basic' },
  { _id: 'IS-1024', code: 'IS-1024', name: 'SEMINARIO DE TESIS', cycle: 10, prerequisites: ['IS-923'], type: 'basic' },
  { _id: 'IS-1021', code: 'IS-1021', name: 'INTELIGENCIA ARTIFICIAL II', cycle: 10, prerequisites: ['IS-921'], type: 'basic' },
  { _id: 'IS-1026', code: 'IS-1026', name: 'PROYECTOS INFORMATICOS II', cycle: 10, prerequisites: ['IS-925'], type: 'basic' },
]
